### ISSUE TITLE
Developer level documentation in wiki

### ISSUE THREAD

**Issue by yashovardhan99** [yashovardhan99/HealersDiary#25]
- [ ] Introduction to the project
- [ ] Gradle guide (dependency management)
- [ ] Modules
- [ ] Onboarding
- [ ] Dashboard
- [ ] Patients
- [ ] Creation
- [ ] Analytics
- [ ] Settings
- [ ] Utils
- [ ] Online module
- [ ] Other coding style and docs
