### ISSUE TITLE
Create a wiki for users

### ISSUE THREAD

**Issue by yashovardhan99** [yashovardhan99/HealersDiary#26]
- [x] Installation Guide
- [ ] Dashboard guide
- [ ] Adding new patient
- [ ] Adding new healing and payment
- [ ] Patient Dashboard
- [ ] Healing, Payment logs
- [ ] Editing patient details
- [ ] Deleting healing, payment
- [ ] Deleting patient
- [ ] Clear data/import guide
